### ISSUE TITLE
Incorrect degree of tau

### ISSUE THREAD

**Issue by chottuthejimmy** [HiteshNP/ML_lab#2]
In [program 9](https://github.com/HiteshNP/ML_lab/blob/main/p9.ipynb)

`xw = (X.T) * np.exp(np.sum((X - x0) ** 2, axis=1) / (-2 * tau))
`

The expression is actually given by

$$ w_i = \exp\left(-\frac{{(x_i - x_0)}^2}{2\tau^2}\right) $$

so its actually `/ (-2 * tau ** 2)`

**Comment by HiteshNP** [comment]
Noted and committed change
